[package]
name = "lightcdc-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
fs2.workspace = true
flume.workspace = true
lightcdc-core = { path = "../lightcdc-core", version = "0.1.0" }
lightcdc-postgres = { path = "../lightcdc-postgres", version = "0.1.0" }
lightcdc-storage = { path = "../lightcdc-storage", version = "0.1.0" }
tokio.workspace = true

[dev-dependencies]
tempfile = "3"
