CREATE USER IF NOT EXISTS 'lightcdc'@'%' IDENTIFIED BY 'lightcdc';
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'lightcdc'@'%';
GRANT INSERT, UPDATE, DELETE, CREATE, DROP, ALTER ON lightcdc.* TO 'lightcdc'@'%';

CREATE TABLE IF NOT EXISTS lightcdc.orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_email VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'created',
    total_cents BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id)
) ENGINE=InnoDB;
