[package]
name = "lightcdc-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lightcdc"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lightcdc-core = { path = "../lightcdc-core", version = "0.1.0" }
lightcdc-api = { path = "../lightcdc-api", version = "0.1.0" }
lightcdc-postgres = { path = "../lightcdc-postgres", version = "0.1.0" }
lightcdc-runtime = { path = "../lightcdc-runtime", version = "0.1.0" }
lightcdc-redis = { path = "../../connectors/lightcdc-redis", version = "0.1.0" }
lightcdc-storage = { path = "../lightcdc-storage", version = "0.1.0" }
hdrhistogram.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = "3"
tokio-postgres.workspace = true
