[package]
name = "lightcdc-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lightcdc-core = { path = "../lightcdc-core", version = "0.1.0" }
lightcdc-storage = { path = "../lightcdc-storage", version = "0.1.0" }
pgwire-replication = "0.4.0"
serde.workspace = true
serde_json.workspace = true
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-postgres-rustls.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
