[package]
name = "lightcdc-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lightcdc-redis"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lightcdc-api = { path = "../../crates/lightcdc-api" }
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = "3"
